/**
 * HTML sanitiser for LLM-generated output.
 *
 * Strips dangerous elements while preserving:
 * - HTML comments (section markers like <!-- bb-section:name -->)
 * - Inline SVG
 * - Netlify Forms attributes (data-netlify, netlify, name)
 * - Relative URLs
 */

// ---------------------------------------------------------------------------
// Patterns
// ---------------------------------------------------------------------------

/** Matches <script>...</script> and self-closing <script /> tags. */
const SCRIPT_TAG_RE = /<script\b[^>]*>[\s\S]*?<\/script\s*>/gi;

/** Matches <iframe>, <object>, <embed> tags (opening or self-closing). */
const DANGEROUS_TAGS_RE = /<\/?(?:iframe|object|embed)\b[^>]*\/?>/gi;

/** Matches event handler attributes like onclick="...", onerror='...'. */
const EVENT_HANDLER_RE = /\s+on[a-z]+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi;

/** Matches javascript: and data: URLs in href/src/action attributes. */
const DANGEROUS_URL_RE =
  /(\s(?:href|src|action)\s*=\s*(?:"|'))(?:javascript|data)\s*:/gi;

/** Matches http:// in href/src attributes (to upgrade to https). */
const HTTP_URL_RE = /(\s(?:href|src)\s*=\s*(?:"|'))http:\/\//gi;

// ---------------------------------------------------------------------------
// Sanitiser
// ---------------------------------------------------------------------------

/**
 * Sanitise HTML generated by Claude.
 *
 * Removes:
 * - <script> tags and contents
 * - Event handler attributes (on*="")
 * - javascript: and data: URLs in href/src/action
 * - <iframe>, <object>, <embed> tags
 *
 * Upgrades:
 * - http:// to https:// in link/src attributes
 *
 * Preserves:
 * - HTML comments (section markers)
 * - Inline SVG
 * - Netlify Forms attributes
 * - Relative URLs
 */
export function sanitiseHtml(html: string): string {
  let sanitised = html;

  // 1. Strip <script> tags and contents
  sanitised = sanitised.replace(SCRIPT_TAG_RE, "");

  // 2. Strip dangerous embed tags
  sanitised = sanitised.replace(DANGEROUS_TAGS_RE, "");

  // 3. Strip event handler attributes
  sanitised = sanitised.replace(EVENT_HANDLER_RE, "");

  // 4. Neutralise javascript: and data: URLs
  sanitised = sanitised.replace(DANGEROUS_URL_RE, "$1about:blank");

  // 5. Upgrade http:// to https:// in links/sources
  sanitised = sanitised.replace(HTTP_URL_RE, "$1https://");

  return sanitised;
}
