/**
 * HTML sanitiser for LLM-generated output.
 *
 * Strips dangerous elements while preserving:
 * - HTML comments (section markers like <!-- bb-section:name -->)
 * - Inline SVG
 * - Netlify Forms attributes (data-netlify, netlify, name)
 * - Relative URLs
 */

// ---------------------------------------------------------------------------
// Patterns
// ---------------------------------------------------------------------------

/** Matches <script>...</script>, self-closing <script />, and unclosed <script> tags. */
const SCRIPT_TAG_RE = /<script\b[^>]*>[\s\S]*?<\/script\s*>/gi;
const UNCLOSED_SCRIPT_RE = /<script\b[^>]*>/gi;

/** Matches <iframe>, <object>, <embed>, <base> tags (opening or self-closing). */
const DANGEROUS_TAGS_RE = /<\/?(?:iframe|object|embed|base)\b[^>]*\/?>/gi;

/** Matches event handler attributes like onclick="...", onerror='...'. */
const EVENT_HANDLER_RE = /\s+on[a-z]+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi;

/**
 * Matches javascript: and data: URLs in href/src/action attributes.
 * Also catches HTML entity-encoded variants (&#106;avascript:, &#x6A;avascript:, etc.)
 */
const DANGEROUS_URL_RE =
  /(\s(?:href|src|action)\s*=\s*(?:"|'))(?:(?:&#x?[0-9a-f]+;?|&#?\w+;?)*\s*j\s*a\s*v\s*a\s*s\s*c\s*r\s*i\s*p\s*t|javascript|data)\s*:/gi;

/** Matches http:// in href/src attributes (to upgrade to https). */
const HTTP_URL_RE = /(\s(?:href|src)\s*=\s*(?:"|'))http:\/\//gi;

// ---------------------------------------------------------------------------
// Sanitiser
// ---------------------------------------------------------------------------

/**
 * Sanitise HTML generated by Claude.
 *
 * Removes:
 * - <script> tags and contents
 * - Event handler attributes (on*="")
 * - javascript: and data: URLs in href/src/action
 * - <iframe>, <object>, <embed> tags
 *
 * Upgrades:
 * - http:// to https:// in link/src attributes
 *
 * Preserves:
 * - HTML comments (section markers)
 * - Inline SVG
 * - Netlify Forms attributes
 * - Relative URLs
 */
export function sanitiseHtml(html: string): string {
  let sanitised = html;

  // 1. Strip <script> tags and contents (closed first, then unclosed)
  sanitised = sanitised.replace(SCRIPT_TAG_RE, "");
  sanitised = sanitised.replace(UNCLOSED_SCRIPT_RE, "");

  // 2. Strip dangerous embed tags (iframe, object, embed, base)
  sanitised = sanitised.replace(DANGEROUS_TAGS_RE, "");

  // 3. Strip event handler attributes
  sanitised = sanitised.replace(EVENT_HANDLER_RE, "");

  // 4. Neutralise javascript: and data: URLs
  sanitised = sanitised.replace(DANGEROUS_URL_RE, "$1about:blank");

  // 5. Upgrade http:// to https:// in links/sources
  sanitised = sanitised.replace(HTTP_URL_RE, "$1https://");

  return sanitised;
}

// ---------------------------------------------------------------------------
// CSS Sanitiser
// ---------------------------------------------------------------------------

/** Strips </style> breakout attempts from CSS strings. */
const STYLE_BREAKOUT_RE = /<\/\s*style\s*>/gi;

/** Strips @import rules that could load external resources. */
const CSS_IMPORT_RE = /@import\s+(?:url\s*\()?[^;]+;?/gi;

/** Strips expression() (IE-era JavaScript-in-CSS). */
const CSS_EXPRESSION_RE = /expression\s*\(/gi;

/** Strips url() with javascript: or data: schemes. */
const CSS_DANGEROUS_URL_RE = /url\s*\(\s*(?:"|')?(?:javascript|data)\s*:/gi;

/**
 * Sanitise CSS generated by Claude.
 *
 * Removes:
 * - </style> breakout sequences (could inject HTML/scripts)
 * - @import rules (could load external stylesheets / exfiltrate data)
 * - expression() (IE JavaScript-in-CSS)
 * - url() with javascript: or data: schemes
 */
export function sanitiseCss(css: string): string {
  let sanitised = css;
  sanitised = sanitised.replace(STYLE_BREAKOUT_RE, "/* blocked */");
  sanitised = sanitised.replace(CSS_IMPORT_RE, "/* blocked */");
  sanitised = sanitised.replace(CSS_EXPRESSION_RE, "/* blocked */(");
  sanitised = sanitised.replace(CSS_DANGEROUS_URL_RE, 'url("about:blank');
  return sanitised;
}
